### ISSUE TITLE
Some images failing to load (mobile?)

### ISSUE THREAD

**Issue by theParadox42** [theParadox42/escape-from-earth#1]
Sometimes, especially images at the end of files.json, fail to load, and don’t display anything causing a bunch of problems.

**Comment by tannerderp** [comment]
I was playing this game on a different computer on microsoft edge. In the space ship scene, the ship kept flashing because one of the ship images didn't load. So it's more than just a mobile problem

**Comment by theParadox42** [comment]
@tannerderp I had that happen once too, I hope these problems don’t get worse as we add more images... 
Here’s a thought, though, I doubt this will work, the very first setup(); is called before the scripts finish loading, so I called new p5(); once they are all loaded, maybe we could load some images there, and some images in the second one. Don’t worry about trying though, I’ll just figure it out. BTW: the images that didn’t load were the ones near the bottom, mostly the Man on the Moon, sometimes the starry background. Both of those are at the end of the files.json, which makes since they would be the ones they didn’t load. I’ll mess around with it tomorrow, and we can figure it out.

**Comment by theParadox42** [comment]
I wonder if it is because the browser can't handle that much data...

**Comment by tannerderp** [comment]
If thats the case then we would probably be screwed

**Comment by theParadox42** [comment]
But it probably is just browsers with high protection, mobile, or plain crapiness, ME

**Comment by tannerderp** [comment]
ya because I've never seen this happen on chrome. Only on satan itself microsoft edge

**Comment by theParadox42** [comment]
Here is an idea, although we could also just say, "YOUR BROWSER IS NOT SUPPORTED, TOM."
What if we loaded all the needed images before the scene, and then trashed them and loaded the next ones at the end of that scene? Just an idea though, maybe I’ll make a branch for it.

**Comment by tannerderp** [comment]
I added level objects to the space scenes, and I used new p5 for a height/2 thing. Now, the whole scene is going WAY faster than it should be. Sooooooooooooooooooooooooooooooooooooo, this whole issue became a lot more confusing
