### ISSUE TITLE
jQuery AJAX(get) not working

### ISSUE THREAD

**Issue by theParadox42** [theParadox42/escape-from-earth#2]
This basically gets stuff from the server, but I can’t get jQuery to get stuff from anywhere...

**Comment by tannerderp** [comment]
I only started backend today, but it looks like you could just load in the JSON with pure javascript
stackoverflow.com/questions/9838812/how-can-i-open-a-json-file-in-javascript-without-jquery

**Comment by theParadox42** [comment]
I got it to work! I did some crappy CORS stuff on the serverside.

**Comment by tannerderp** [comment]
Man whoever made CORS must of been a weasel
